### ISSUE TITLE
Issues with certbot import

### ISSUE THREAD

**Issue by zimme** [NginxProxyManager/nginx-proxy-manager#4365]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I'm getting this after an upgrade from 2.11.3 to 2.12.3
```
nginx-proxy-manager-1  | [2/13/2025] [12:17:26 PM] [Global   ] › ⬤  debug     CMD: /usr/sbin/nginx -s reload
nginx-proxy-manager-1  | [2/13/2025] [12:17:30 PM] [Express  ] › ⚠  warning   Traceback (most recent call last):
nginx-proxy-manager-1  |   File "/opt/certbot/bin/certbot", line 5, in <module>
nginx-proxy-manager-1  |     from certbot.main import main
nginx-proxy-manager-1  | ImportError: cannot import name 'main' from 'certbot.main' (/opt/certbot/lib/python3.11/site-packages/certbot/main.py)
nginx-proxy-manager-1  |
```

**Nginx Proxy Manager Version**

2.12.3

**To Reproduce**
Try to issue a let's encrypt cert for a domain.

**Expected behavior**

Should be able to issue the cert.

**Screenshots**

**Operating System**

Docker on Ubuntu 24.04 

**Additional context**
