### ISSUE TITLE
Cannot import 'ClientBase' from 'acme.client' when trying to renew cert(s)

### ISSUE THREAD

**Issue by phillipmcmahon** [NginxProxyManager/nginx-proxy-manager#3245]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When trying to renew existing certs after updating to 2.10.4 get an internal error. Logs show the following

[10/7/2023] [10:53:22 AM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates via ClouDNS for Cert #17: *.phillipmcmahon.com, phillipmcmahon.com
[10/7/2023] [10:53:22 AM] [SSL      ] › ℹ  info      Command: certbot renew --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-17" --disable-hook-validation --no-random-sleep-on-renew 
[10/7/2023] [10:53:22 AM] [Express  ] › ⚠  warning   Command failed: certbot renew --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-17" --disable-hook-validation --no-random-sleep-on-renew 
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in <module>
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in <module>
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in <module>
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

**Nginx Proxy Manager Version**
2.10.4

**To Reproduce**
1. Go to SSL Certificates
2. Click on 'Renew Now' for the certificate in question
3. 'Internal Error' in UI

**Expected behavior**
Certificate renews as expected

**Screenshots**

<img width="1217" alt="image" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/1891527/00db8db4-ac69-4dc2-95b5-f76f0142584e">

**Operating System**
via Docker

**Additional context**
N/A

**Comment by decole** [comment]
I have this bug too.

**Comment by NetRat88** [comment]
Also same bug for me. Found out on reddit a possible workaroung. Replce acme==1.32.0 seems to make it work on Godaddy DNS

**Comment by Clasher31HD** [comment]
I also have this issue

**Comment by ozzyobr** [comment]
Anyone found a solution? I'm having the same problem.

**Comment by Syirrus** [comment]
I have this same error. Is there a solution for the issue?

**Comment by ismxilxrif** [comment]
i don't know what's the issue, i created a new virtual environment inside my home directory (non-root), and link /usr/bin/certbot to that new venv, and the problem's solved, note bcs of wildcard issue, i used certbot-dns-godaddy==2.6.0

it's just my 2 cents, but it might help some folks out there, good luck!

**Comment by SNR-Tech-Bytes** [comment]
for those of you in docker I seem to have fixed this using some information I found on [reddit](https://www.reddit.com/r/nginxproxymanager/comments/166fbka/certbot_renew_internal_error/)
Note I'm using godaddy DNS challenge

run the following
`docker compose ps`
which will will spit out your list of dockers, whatever your nginx proxy manager is named put that in the following command

'docker exec [your_docker_name_no_Braces] /bin/sh -c "/opt/certbot/bin/pip install acme==1.32.0"'

**Comment by Ragziesoft** [comment]
> for those of you in docker I seem to have fixed this using some information I found on [reddit](https://www.reddit.com/r/nginxproxymanager/comments/166fbka/certbot_renew_internal_error/) Note I'm using godaddy DNS challenge
> 
> run the following
> 
> `docker compose ps`
> 
> which will will spit out your list of dockers, whatever your nginx proxy manager is named put that in the following command
> 
> `docker exec [your_docker_name_no_Braces] /bin/sh -c "/opt/certbot/bin/pip install acme==1.32.0"`

I tried this but i am still getting internal error. The acme was changed to 1.32.0
