### ISSUE TITLE
Uncaught TypeError: e.split is not a function when migrating from 2.12.6 to 2.13.1

### ISSUE THREAD

**Issue by vsc55** [NginxProxyManager/nginx-proxy-manager#4844]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
After updating from version 2.12.6 to 2.13.1, when accessing some sections, no content is displayed and a JavaScript error is generated.

**Nginx Proxy Manager Version**
2.13.1

**To Reproduce**
1. Go to 'Proxy Host' or 'Certificates'
2. It does not display content and a JavaScript error is generated.

**Screenshots**
<img width="1671" height="738" alt="Image" src="https://github.com/user-attachments/assets/c2a49582-7883-45af-a50f-766748f12097" />

**Operating System**
linux x86_64 Debian GNU/Linux 13 (trixie)
Docker: 28.5.1 (API: 1.51)

**Additional context**
I have tested with Firefox and Chrome, both in normal and private sessions.

Error JS:
```
Uncaught TypeError: e.split is not a function
    $M https://iproxy.domain.local/assets/index-BBAG1AZl.js:126
    z8 https://iproxy.domain.local/assets/index-BBAG1AZl.js:126
    pE https://iproxy.domain.local/assets/index-BBAG1AZl.js:126
    p https://iproxy.domain.local/assets/DomainsFormatter-DRGLydBn.js:1
    ld https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    M0 https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    nS https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    LS https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    aI https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    tg https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    xS https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    qS https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    Ad https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    GS https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    dI https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    dI https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    Li https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ar https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    iT https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    aT https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    batchCalls https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    n https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    u https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    u https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    a https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    u https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    setTimeout handler*uR https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    u https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    batch https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    #i https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    setData https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    fetch https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    #d https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    onSubscribe https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    subscribe https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    UR https://iproxy.domain.local/assets/index-BBAG1AZl.js:50
    aT https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    bd https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    ES https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
    si https://iproxy.domain.local/assets/index-BBAG1AZl.js:49
index-BBAG1AZl.js:126:13026
```

Console Docker:
```
-------------------------------------
User:  npm PUID:0 ID:0 GROUP:0
Group: npm PGID:0 ID:0
-------------------------------------
❯ Starting nginx ...
❯ Starting backend ...
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /data/nginx/proxy_host/32.conf:19
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /data/nginx/redirection_host/1.conf:15
nginx: [warn] protocol options redefined for 0.0.0.0:443 in /data/nginx/redirection_host/1.conf:15
nginx: [warn] protocol options redefined for 0.0.0.0:443 in /data/nginx/redirection_host/2.conf:15
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /data/nginx/dead_host/1.conf:15
nginx: [warn] protocol options redefined for 0.0.0.0:443 in /data/nginx/dead_host/1.conf:15
[11/5/2025] [9:06:11 AM] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
[11/5/2025] [9:06:11 AM] [Global   ] › ⬤  debug     Checking for keys file: /data/keys.json
[11/5/2025] [9:06:11 AM] [Global   ] › ℹ  info      Keys file exists OK
[11/5/2025] [9:06:11 AM] [Migrate  ] › ℹ  info      Current database version: none
[11/5/2025] [9:06:11 AM] [Global   ] › ⬤  debug     CMD: [ -f '/etc/letsencrypt/credentials/credentials-42' ] || {....}
[11/5/2025] [9:06:11 AM] [Certbot  ] › ▶  start     Installing namecheap...
[11/5/2025] [9:06:11 AM] [Global   ] › ⬤  debug     CMD: . /opt/certbot/bin/activate && pip install --no-cache-dir  certbot-dns-namecheap~=1.0.0  && deactivate
[11/5/2025] [9:06:19 AM] [Certbot  ] › ☒  complete  Installed namecheap
[11/5/2025] [9:06:19 AM] [Setup    ] › ℹ  info      Added Certbot plugins namecheap
[11/5/2025] [9:06:19 AM] [Setup    ] › ℹ  info      Logrotate Timer initialized
[11/5/2025] [9:06:19 AM] [Global   ] › ⬤  debug     CMD: logrotate /etc/logrotate.d/nginx-proxy-manager
[11/5/2025] [9:06:19 AM] [Setup    ] › ℹ  info      Logrotate completed.
[11/5/2025] [9:06:19 AM] [Global   ] › ℹ  info      IP Ranges fetch is enabled
[11/5/2025] [9:06:19 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[11/5/2025] [9:06:19 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[11/5/2025] [9:06:19 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[11/5/2025] [9:06:19 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[11/5/2025] [9:06:19 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[11/5/2025] [9:06:19 AM] [SSL      ] › ℹ  info      Renewing SSL certs expiring within 30 days ...
[11/5/2025] [9:06:19 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[11/5/2025] [9:06:19 AM] [Global   ] › ℹ  info      Backend PID 220 listening on port 3000 ...
[11/5/2025] [9:06:19 AM] [SSL      ] › ℹ  info      Completed SSL cert renew process
```

**Comment by vsc55** [comment]
Hello again.
I've been reviewing the database and I think the problem is related to the date.
I have older records in the SQLite database in Unix format, and the newer ones are in ISO format.
I tried the "Redirection Hosts" section, which wasn't loading, but after manually updating the created_on and modified_on values ​​from Unix to ISO, it started loading.
Should I add a system for updating this data to the update process?

Example:

<img width="1078" height="528" alt="Image" src="https://github.com/user-attachments/assets/22b79ed6-fba6-4196-9944-2b8fda3cd6e0" />

**Comment by Santya95** [comment]
<img width="500" height="209" alt="Image" src="https://github.com/user-attachments/assets/0e7cd68e-0b9c-4b04-b09f-72b1e9fd7c7c" />

same here when clicking on certificates

**Comment by vsc55** [comment]
Hi @jc21,

I can confirm that the problem is due to the date format.

I've updated "created_on", "modified_on", and a few other columns like "expires_on" in the certificates table, and now everything is working again.

This is the query I used on each table that had incorrectly formatted dates:
```sql
UPDATE certificate
SET created_on = CASE
  WHEN created_on GLOB '[0-9]*' AND CAST(created_on AS INTEGER) > 9999999999
    THEN strftime('%Y-%m-%d %H:%M:%S', CAST(created_on AS INTEGER)/1000, 'unixepoch')
  WHEN created_on GLOB '[0-9]*'
    THEN strftime('%Y-%m-%d %H:%M:%S', CAST(created_on AS INTEGER), 'unixepoch')
  ELSE created_on
END
WHERE created_on GLOB '[0-9]*'
  AND created_on NOT LIKE '____-__-__%';
```

```sql
UPDATE certificate
SET modified_on  = CASE
  WHEN modified_on  GLOB '[0-9]*' AND CAST(modified_on  AS INTEGER) > 9999999999
    THEN strftime('%Y-%m-%d %H:%M:%S', CAST(modified_on  AS INTEGER)/1000, 'unixepoch')
  WHEN modified_on  GLOB '[0-9]*'
    THEN strftime('%Y-%m-%d %H:%M:%S', CAST(modified_on  AS INTEGER), 'unixepoch')
  ELSE modified_on 
END
WHERE modified_on GLOB '[0-9]*'
  AND modified_on NOT LIKE '____-__-__%';
```

**Comment by jc21** [comment]
Thanks for figuring this out. The migrations only ever create this field once and don't modify it. The knex package is meant to handle the column type per engine for us. Not sure how there's 2 different data types in the same column there...

I think I could create a migration file based on your sql but it should only be specific to sqlite.

**Comment by vsc55** [comment]
@jc21 I ran that query exactly as it is in my SQLite database and it worked correctly.
As I mentioned, you have to consider not only the "created_on" and "modified_on" columns. There are tables like "certificates" that also have date columns that cause problems, such as "expires_on," or "migration_time" in the "migrations" table.

**Comment by jc21** [comment]
yeah.. either that or I have to write frontend js to handle both data types

**Comment by vsc55** [comment]
It appears to be a bug in Knex.
https://github.com/knex/knex/issues/5240

**Comment by jc21** [comment]
How fun :/ and it's still open..

I've made the frontend fixes for support both types and not crash if there's bad data in date fields.

Please test with this docker image and let me know:

```
nginxproxymanager/nginx-proxy-manager-dev:develop
```

**Comment by vsc55** [comment]
Hi @jc21,

With this image everything works except the **certificates** section which continues to generate the error.

**Comment by jc21** [comment]
Thanks @vsc55. The git push with that fix has closed the issue, but still needs another test using the same image, ensuring you pull the fresh one I just built.

```
nginxproxymanager/nginx-proxy-manager-dev:develop
```

**Comment by vsc55** [comment]
Hi @jc21,

I tested it with the new Docker and now it works correctly. 👌
