### ISSUE TITLE
Unable to add any SSL certificate

### ISSUE THREAD

**Issue by andrewhaji** [NginxProxyManager/nginx-proxy-manager#2420]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I am having issues with creating SSL certificates. Both HTTP and DNS certificates cannot be created despite the server being reachable. I am receiving the following error no matter what kind of certificate I try to generate:

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-15" --agree-tos --authenticator webroot --email "MYEMAIL" --preferred-challenges "dns,http" --domains "THE.DOMAIN" 
An unexpected error occurred:
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-3c90t_tk/log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Nginx Proxy Manager Version**

2.9.19

**To Reproduce**
Go to SSL Certificates
Add SSL Certificate
Type in domain, agree to terms, and click Save
Error is displayed

**Expected behavior**

It should be generating the SSL certificate

**Screenshots**

**Operating System**

Using docker latest image running on Ubuntu 22.04

**Additional context**

What's strange is that certificate generation works on ONE of my installs running 2.9.19, but THREE other installs all fail. They have all been able to generate SSL certificates in the past. Never been an issue until now.

**Comment by andrewhaji** [comment]
During my troubleshooting process I wiped out my NPM configuration and started from scratch. When starting from scratch I had no trouble generating the necessary SSL certificates.

So something in my existing NPM installations must be causing this issue - it's happening on 3 different machines that were set up at different times.

**Comment by Gedimz** [comment]
I have the same problem and the same solution seems to help, for a short period of time

**Comment by spoit** [comment]
I have this issue too. Tried reinstalling but did not help

Could [this](https://github.com/certbot/certbot/issues/9427#issuecomment-1271019939) be related?

**Comment by andrewhaji** [comment]
> Could [this](https://github.com/certbot/certbot/issues/9427#issuecomment-1271019939) be related?

The error message is the same as what I'm seeing. Does Nginx Proxy Manager use Certbot 2.0 internally? Version 2.0.0 was released only 3 days ago, and the latest Nginx Proxy Manager docker image was built over 2 weeks ago. Unless the docker image downloads the latest Certbot upon first run? I admit I'm not a docker expert.

Additionally, the breaking change seems to be related to DNS certificates only, not HTTP? I'm getting this error message even when generating an HTTP certificate.

**Comment by spoit** [comment]
I'm only getting the error when trying to add SSL certificates (via gandi livedns):

```
Error: Command failed: certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  

An unexpected error occurred:

AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
```

**Comment by sam-semillia** [comment]
same issue on my side, using netcup dns :/

**Comment by spoit** [comment]
Possibly related to https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2430 and/or https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2427
